version: 1.17.{build}.0
image: Visual Studio 2019
platform:
- x86
- x64
configuration:
- Release_DLL
install:
- cmd: git submodule -q update --init
before_build:
- ps: Invoke-WebRequest "https://github.com/nefarius/vpatch/releases/latest/download/vpatch.exe" -OutFile vpatch.exe
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\%APPVEYOR_PROJECT_NAME%.vcxproj" --vcxproj.inf-time-stamp
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\%APPVEYOR_PROJECT_NAME%.rc" --resource.file-version --resource.product-version
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
artifacts:
- path: 'bin**\*.lib'
- path: 'bin**\*.dll'
- path: 'bin**\*.pdb'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true