name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch vJoy SDK
        run: |
          Invoke-WebRequest `
            "https://github.com/njz3/vJoy/releases/download/v2.2.1.1/vJoy-2.2.1.1-SDK.zip" `
            -Out vJoy-SDK.zip
      - name: Extract vJoy SDK
        run: |
          Expand-Archive vJoy-SDK.zip .
          cp SDK\lib\vJoyInterface.dll .
      - name: Build (Release)
        run: .\build.ps1 all
      - name: Build (Debug)
        run: .\build.ps1 all -BuildMode Debug
      - name: Run test (Debug)
        run: .\test-Debug.exe
