name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ Win32, Win64 ]
        mode: [ RelWithDebInfo, Debug ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -A ${{matrix.platform}
      - name: Build
        working_directory: build
        run: cmake --build . --config ${{matrix.mode}} --parallel
      - name: Run tests
        run: build/tests/${{matrix.config}}/test.exe
