name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch vJoy SDK
        run: |
          Invoke-WebRequest `
            "https://github.com/njz3/vJoy/releases/download/v2.2.1.1/vJoy-2.2.1.1-SDK.zip" `
            -Out vJoy-SDK.zip
      - name: Extract vJoy SDK
        run: Expand-Archive vJoy-SDK.zip .
      - uses: microsoft/setup-msbuild@v1.0.2
        with:
          toolset: 18.6
      - name: Build example
        run: .\build.ps1 example
      - name: Build list-devices
        run: .\build.ps1 list-devices
