name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [ RelWithDebInfo, Debug ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build
        working-directory: build
        run: cmake --build . --config ${{matrix.mode}} --parallel
      - name: Install
        working-directory: build
        run: cmake --install . --config ${{matrix.mode}} --prefix ${{runner.temp}}/install
      - name: Run tests
        working-directory: ${{runner.temp}}/install
        run: test.exe
