name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [ RelWithDebInfo, Debug ]
        compiler: [ cl, clang]
        platform: [ x86, x64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: |
          $CMakeArgs = @()

          if ("${{matrix.compiler}}" -eq "clang") {
            $CMakeArgs += @(-T ClangCL)
          }
          if ("${{matrix.platform}}" -eq "x86") {
            $CMakeArgs += @(-A Win32)
          }
          mkdir build
          cd build
          Write-Output("Running: cmake .. @CMakeArgs")
          cmake .. @CMakeArgs
      - name: Build
        working-directory: build
        run: cmake --build . --config ${{matrix.mode}} --parallel
      - name: Install
        working-directory: build
        run: cmake --install . --config ${{matrix.mode}} --prefix ${{runner.temp}}/install
      - name: Run tests
        working-directory: ${{runner.temp}}/install
        run: bin/test.exe
