name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch vJoy SDK
        run: |
          Invoke-WebRequest `
            "https://github.com/njz3/vJoy/releases/download/v2.2.1.1/vJoy-2.2.1.1-SDK.zip" `
            -Out vJoy-SDK.zip
      - name: Extract vJoy SDK
        run: |
          Expand-Archive vJoy-SDK.zip .
          cp SDK\lib\vJoyInterface.dll .
      - name: Build example
        run: .\build.ps1 example.cpp
      - name: Build list-devices
        run: .\build.ps1 list-devices.cpp
      - name: Build test
        run: .\build.ps1 test.cpp
      - name: Run test
        run: .\test.exe
