name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ x86, x64 ]
        mode: [ Release, Debug ]
        compiler: [ clang, cl ]
        exclude:
          - compiler: clang
            platform: x86
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch vJoy SDK
        run: |
          Invoke-WebRequest `
            "https://github.com/njz3/vJoy/releases/download/v2.2.1.1/vJoy-2.2.1.1-SDK.zip" `
            -Out vJoy-SDK.zip
      - name: Extract vJoy SDK
        run: |
          Expand-Archive vJoy-SDK.zip third-party\vJoy
          if ( "${{matrix.platform}}" -eq "x64" ) {
            cp SDK\lib\amd64\vJoyInterface.dll .
          } else {
            cp SDK\lib\vJoyInterface.dll .
          }
      - name: Build
        run: |
          .\build.ps1 all `
            -BuildMode ${{matrix.mode}} `
            -Platform ${{matrix.platform}} `
            -Compiler ${{matrix.compiler}}
      - name: Run tests
        run: |
          $ExeSuffix = .\build.ps1 all `
            -BuildMode ${{matrix.mode}} `
            -Platform ${{matrix.platform}} `
            -Compiler ${{matrix.compiler}} `
            -ShowExeSuffix
          & .\bin\test${ExeSuffix}.exe
